version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_main
    environment:
      POSTGRES_USER: test_777 # Пользователь PostgreSQL
      POSTGRES_PASSWORD: test_777 # Пароль PostgreSQL
      POSTGRES_DB: postgres # Название основной базы данных PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - project_ci_cd
    
  app:
    build:
      context: .
    command: /app/wait-for-it.sh postgres:5432 -- uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app
      DB_USER: test_777 # Пользователь PostgreSQL
      DB_PASS: test_777 # Пароль PostgreSQL
      DB_HOST: db
      DB_NAME: postgres # Название основной базы данных PostgreSQL
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - project_ci_cd

  
volumes:
  postgres_data:

networks:
  project_ci_cd:
